sequenceDiagram
    participant browser
    participant server

    browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server -->> browser: HTTP Status 200 - Ok Return text/html
    deactivate server

    browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server -->> browser: HTTP Status 200 - OK Return text/css
    deactivate server

    browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server
    server -->> browser: HTTP Status 200 - OK Return application/javascript
    deactivate server

    browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server -->> browser: HTTP Status 200 - OK Return aplication/json
    deactivate server
    Note right of browser: The browser executes the callback function that renders the notes

